### ISSUE TITLE
Hello! I would be willing to see benchmarks against these frameworks.

### ISSUE THREAD

**Issue by iogf** [vibora-io/vibora#104]
Server
https://github.com/untwisted/rapidserv

Client
https://github.com/untwisted/websnake

**Comment by frnkvieira** [comment]
The project seems to be abandoned, it's Python 2 only (tried to run the README example and failed because of Python 2 syntax), I think there are a lot of frameworks who deserve to be on the benchmarks first, in case you insist, please do a pull request at https://github.com/vibora-io/benchmarks and I'll be glad to include it in the next round. Feel free to open this issue if you think I'm wrong, I appreciate your feedback, thanks!
