### ISSUE TITLE
[Feature Request] conditions in template handler 

### ISSUE THREAD

**Issue by lepeli** [vibora-io/vibora#137]
Hello, 
I would like to ask for conditions  in the template handler. 
Because this is the feature I used a lot in jinja2.

Thanks in advance

**Comment by danieldaeschle** [comment]
If it isn't implemented yet it will be implemented soon. This repository is in alpha state and not ready for production.

**Comment by frnkvieira** [comment]
@lepeli what do you mean by "conditionals"?

- In case you mean IF/FOR control structures we already support them. If you need something more sophisticated please let me know.
- In case you mean conditional "extends" statements or "block" structures these are currently not supported because this prevents a lot of optimizations since you need to evaluate parent templates at runtime (and open several windows to introduce bugs) instead of pre-compiling everything... With a bit of creativity, this should not be a major problem.

Let me know what you think, I appreciate your feedback, thanks!

**Comment by danieldaeschle** [comment]
How do you precompile for loops? You don't know which data is given in template. You have to compile it just in time always or i am wrong?

**Comment by frnkvieira** [comment]
@danieldaeschle Templates are parsed and compiled just-in-time. (this do not means they are **pre-rendered**... they are compiled into an AST which is then compiled to a function that produces the expected results)

**Comment by danieldaeschle** [comment]
Wow, that is very interesting ;)
Which is the source of it? I have to read your code!

**Comment by lepeli** [comment]
@danieldaeschle  Yeah it was for "if" control structures.

Thanks for your answer.
