### ISSUE TITLE
when the v1.0 coming?

### ISSUE THREAD

**Issue by yxxhero** [vibora-io/vibora#204]
when the v1.0 coming?

**Comment by danieldaeschle** [comment]
I hope this month, but i think never :smile:

**Comment by yxxhero** [comment]
do you kuow why?  i like vibora

**Comment by danieldaeschle** [comment]
Frank is a little bit busy. He is working on a better release which should container all final stuff.
He said he want to release it on september (he doesn't said which september) but his last state was that he's looking for some names for third party modules for vibora like schemas or templating.
Another thing was that he's unclear if he split vibora in multiple modules or let it be in one big module. I think he choosed the first one.

He's also adding 100% test coverage which needs its time. Please be patient. I think the next release is coming on one or (worst case) two months. 😄

**Comment by yxxhero** [comment]
thank you!  thank open source! i am a chinese people, thank your answer... my englist is not good

**Comment by NullDereference** [comment]
I'm a huge fan of the design and usage of Vibora, but you should really push out a new release version if the entire codebase is crippled simply by a new reserved keyword.

**Comment by py-radicz** [comment]
hey, how the version 1 is doing? 

- thanks for the awesome project

**Comment by sylvoslee** [comment]
when the v1.0 coming?

**Comment by danieldaeschle** [comment]
Please read my commet dudes...

**Comment by wooque** [comment]
No commits in more than 3 months. Is project dead?

**Comment by DanielSokil** [comment]
@wooque Only 3 months.

**Comment by jefcolbi** [comment]
go ahead frank. i have a future project that i want to use with vibora. i know you said that it can not be used be used in production but i am enthusiast

**Comment by sylvoslee** [comment]
Any news

**Comment by danieldaeschle** [comment]
In Dezember a update is coming. Before Christmas he will push a branch.

**Comment by yxxhero** [comment]
Christmas will come！！！

**Comment by jefcolbi** [comment]
D-5 remaining xD

**Comment by yxxhero** [comment]
Christmas is coming！！！

**Comment by thelostscientist** [comment]
Christmas is here!

**Comment by sylvoslee** [comment]
Bounced check

**Comment by pauldevos** [comment]
As far as contributing goes (helping)... I suppose this project is a bit on hold due to the total refactoring? As unless there's an outline of how it would be implemented, one would, if trying to contribute/build on this, would just be building on a different fork altogether. Does that seem a correct assertion?

**Comment by supposedly** [comment]
Here's hoping 2019 proves early on to be the Year of the Viper :)

**Comment by scil** [comment]
until v1.0, [responder](https://github.com/kennethreitz/responder) powered by starlette can be used.
Or anything else?

**Comment by andreheringer** [comment]
Hi guys, so I've emailed Frank (the project author) last year in Nov and ask him if everything was ok. He said he was busy because he was moving away from Brazil and after it's all settled he would get back to work on Vibora. Since then haven't heard of him. I can try to get in contact with him again and ask if he has plans on getting back to Vibora. But maybe we should start a new fork.

I really like what Vibora does especially with Cython. Although I've never maintained a repo I would be happy to help in any way I can. Maybe @danieldaeschle could fork it, since he is the biggest contributor after Frank. I don't know.

I'll try contact Frank again and see if its ok to start a fork or something if he can't come back, I just don't want Vibora to die.

If anyone has any other suggestions and want to share please reply 😄 , I'm new to this Open Source stuff so I don't know what else to do.

**Comment by danieldaeschle** [comment]
He is rewriting Vibora completely. Give him some more time and use Sanic instead.

Forking this project isn't really a good option since it isn't usable in production. It's just early alpha at the moment.

**Comment by frnkvieira** [comment]
Just updated the README so I think this issue is not needed anymore.
And yes, I'm late, happy new year and thanks for the support :)

**Comment by frnkvieira** [comment]
@jefcolbi I'll add Vibora to techempower.
