### ISSUE TITLE
Is there any plan to add CORS support to vibora ?

### ISSUE THREAD

**Issue by GoodManWEN** [vibora-io/vibora#251]
Vibora is such a lovely framework who is fast ,and elegant .However I couldn't find any information about CORS in docs . I mean , it's regretful that if here's such a fast framework but you can't use it to build cross origin apis ,isn't it ?

Will you provides CORS supports in future? OR this feature is already exists and I just miss something in docs. Looking forward to replies, thanks.

**Comment by Otoru** [comment]
To work with CORS it is necessary to deal with two points:

- Add the `Access-Control-Allow-Origin` header in the responses.
- Handle **PRE-FLIGHT** requests.

In a simplified form, PRE-FLIGHT requests are **OPTION** method requests that have the following formed:

```
OPTIONS /recurso/12345
User-Agent: Mozilla/5.0 
Access-Control-Request-Method: DELETE
Access-Control-Request-Headers: origin, x-requested-with, accept
```
**Note**: This is a PRE-FLIGHT request that occurs when the front end tries to make a DELETE request to the backend.

The answer should look like this:
```
HTTP/1.1 200 OK
Date: Wed, 20 Nov 2013 19:36:00 GMT
Server: Nginx
Content-Length: 0
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE
```

Therefore, to deal with CORS within Vibora, I believe the following line of thought should be followed:

- When an instance of `Vibora` is defined, a `cors` parameter can be defined (its default value will be `None`.

- For each received request, it will be necessary to check whether source host is within the list reported in cors or if cors is equal to `*`.

- If any of the queries are positive, the response must contain an `Access-Control-Allow-Origin` header equal to the request host or `*`.

- If the request is of the **OPTION** method, then return a **200 Ok** with the `Access-Control-Allow-Origin` and `Access-Control-Allow-Methods` headings, the first one follows the previously described logic and the second one is a list of methods supported by the endpoint.

I believe that this could be done in a blueprint for an isolated case, but I also plan to do a PR with the implementation of the resource so that everyone contributes continuously with the resource, but rather it would be interesting to have the opinion of the project maintainers, a instead they may consider that this would be the role of a plugin.

Note: The logic described above is just a sketch and needs to be improved. I just tried to give the initial path of the process.

**Comment by RemiDesgrange** [comment]
You need more than one header to control CORS, From my understanding, there is at least 3:

* `Access-Control-Allow-Origin`
* `Access-Control-Allow-Methods`
* `Access-Control-Allow-Headers`

Mozilla have a good doc about it : https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Now from a Vibora and API perspective. I think we could have an object, named `CORSRule` which describe a CORS rule, like:

```
CORSRule(path="*", 
                  headers=["Content-Type"]  # warn, this should be case-insensitive dict
                  methods=['GET', 'POST')
```
There should be default values for `headers` and `methods`. You could create many `CORSRule` object and then pass it to a `cors` option in the `Vibora` object.

Another cool stuff could be to add specific cors rule as a decorator like:

```
@app.route('/my_route')
@app.cors(headers=['Content-Type'],  methods=['GET'])
def my_route():
    pass
```
But if the route is infer from the previous decorator it will be cumbersome and error prone for new comers, so this is just an idea, or a seed of an idea :-). But having cors definitions next to a route definition could definitely helps troubleshooting.

**Comment by Otoru** [comment]
The previous comment is really a great basis for new framework functionality.  If there was a positive sign from the project maintainer and the possibility of this happening, I would be happy to work with the rest of the community on a branch to implement this functionality.
