### ISSUE TITLE
Remove "sexy" terminology from project

### ISSUE THREAD

**Issue by justinmayer** [vibora-io/vibora#58]
(@frnkvieira: Congratulations on attracting attention to your project. When folks provide critical feedback, even when said feedback is not conveyed in the most constructive manner, I would encourage you to respond as gracefully and non-defensively as you can. This is not easy, and I am terrible at it. 😄  Nevertheless, I hope you will apply this practice when thinking about how you want to handle this issue.)

As [noted](https://twitter.com/tintvrtkovic/status/1010140759578824704) by [others](https://twitter.com/squeaky_pl/status/1010203603448066048) in the [python community](https://twitter.com/hynek/status/1010204441369333761), usage of the word "sexy" to describe this project:

* is often perceived as juvenile
* is not welcoming or inclusive
* can pre-select an undesirable audience (namely, immature dude-bros)

Here are the references to the word in question:
https://github.com/vibora-io/vibora/search?q=sexy&type=Code

I recommend that these references be removed. They provide no value and are only a detriment to the project.

**Comment by Princesseuh** [comment]
I find some of the comments to be quite unfair to @frnkvieira or at least like you said, ungraceful. 

In addition of Vibora seemingly being his first contribution to open source, he's clearly not a native speaker, complaints regarding terminology and language should, in my opinion, be expressed in a more understanding way considering those facts. 

As for the issue, like @frnkvieira, I personally don't find the term to be a problem (also being a non-native speaker) but if it make people feel unwelcome (among other cited issues), I'm definitely all for replacing it. 

I prefer replacing it then just removing it, since it put emphasis on the relatively minimalist approach of Vibora (regarding boilerplate code). Maybe other frameworks with similar approach could be looked at for inspiration regarding this? Perhaps [Rocket](https://rocket.rs/)?

**Comment by Zheaoli** [comment]
I'm not a native English speaker.

In my opinion, the Sexy word is easy to understand. I will realize it's beautiful and powerful framework.

So I don't think this should be a problem.

**Comment by frnkvieira** [comment]
Hello :)
Well, it was **never my intention** to offend anyone and by yesterday I didn't even know what "bro-ish" and "dude-bros" means so I think replacing it may be the way to go. 

I chose "sexy" because I really care about design be it on minimalist APIs or in the logo, website, everything... It was pretty much like "beautiful" to me but I wanted something unique. As you can see this is the problem of international stuff, different cultures, languages and opinions :) 

So now English speakers, help me find a replacing word :)

**Comment by rubik** [comment]
@frnkvieira I don't think "sexy" conveys what you described in this last comment. Maybe minimalist/essential are better words. I particularly like "essential" because it gives the idea that Vibora focuses on the core parts without being bloated. Essential & efficient sounds good as well.

**Comment by manugarri** [comment]
I would say maybe @justinmayer concern is not a worldwide concern, but a concern for specific countries (some of them english speakers).

The easy thing would be to remove the word. But I am sure there are other words that are offensive to other non english speaking countries that would not be removed for the sake of freedom of expression.

**Comment by Mariatta** [comment]
Thanks for this discussion. I agree with @justinmayer, I suggest removing "sexy".
I like @samdoiron's suggestion: "elegant".

**Comment by rubik** [comment]
@manugarri It is not offensive, it is out of place. Since the website is in English, we should be concerned about using English words correctly, without thinking of all the possible interpretations of non-English speakers. I second the suggestion for "elegant".

**Comment by frnkvieira** [comment]
Sexy was replaced by elegant. CDN will take some time but the repository is done. Thank you all.

**Comment by DanielSokil** [comment]
[Voluptuous](http://www.dictionary.com/browse/voluptuous), could be an option
